module.exports = {
    'angle': function() { /* stub */ },
    'basic-shape': function() { /* stub */ },
    'blend-mode': function() { /* stub */ },
    'color': function() { /* stub */ },
    'custom-ident': function() { /* stub */ },
    'frequency': function() { /* stub */ },
    'gradient': function() { /* stub */ },
    'image': function() { /* stub */ },
    'integer': function() { /* stub */ },
    'length': function() { /* stub */ },
    'number': function() { /* stub */ },
    'percentage': function() { /* stub */ },
    'position': function() { /* stub */ },
    'ratio': function() { /* stub */ },
    'resolution': function() { /* stub */ },
    'shape': function() { /* stub */ },
    'string': function() { /* stub */ },
    'time': function() { /* stub */ },
    'timing-function': function() { /* stub */ },
    'transform-function': function() { /* stub */ },
    'url': function() { /* stub */ },
    'user-ident': function() { /* stub */ }
};
