module.exports = {
    'angle': function() { /* stub */ },
    'attr-name': function() { /* stub */ },
    'attr-fallback': function() { /* stub */ },
    'basic-shape': function() { /* stub */ },
    'blend-mode': function() { /* stub */ },
    'color': function() { /* stub */ },
    'custom-ident': function() { /* stub */ },
    'dimension': function() { /* stub */ },
    'frequency': function() { /* stub */ },
    'flex': function() { /* stub */ }, // https://drafts.csswg.org/css-grid/#fr-unit
    'gradient': function() { /* stub */ },
    'hex-color': function() { /* stub */ },
    'id-selector': function() { /* stub */ }, // element( <id-selector> )
    'ident': function() { /* stub */ },
    'image': function() { /* stub */ },
    'integer': function() { /* stub */ },
    'length': function() { /* stub */ },
    'number': function() { /* stub */ },
    'percentage': function() { /* stub */ },
    'position': function() { /* stub */ },
    'positive-integer': function() { /* stub */ },
    'ratio': function() { /* stub */ },
    'resolution': function() { /* stub */ },
    'shape': function() { /* stub */ },
    'string': function() { /* stub */ },
    'time': function() { /* stub */ },
    'timing-function': function() { /* stub */ },
    'transform-function': function() { /* stub */ },
    'url': function() { /* stub */ },
    'user-ident': function() { /* stub */ }
};
